import {get,set,rows,runtimeName,remove} from './state';import {connection} from './vault';import {publicHttps} from '../agent/http';import {validateShared,sharedSnapshot,shareable,type SharedContext} from '../agent/shared-context';import {putContextRecord,removeContextRecord} from './record-store';import {fingerprint,redact} from '../agent/operations';
const contextHash=(records:import('../agent/types').WorkspaceRecord[])=>fingerprint(records.map(({id,kind,name,content})=>({id,kind,name,content})).sort((a,b)=>a.id.localeCompare(b.id)));
type Link={connectionId:string;autoPull:boolean;revision:number;localHash?:string};
export async function hubLink(who:string){return (await get<Link>(who,'sys:device-hub'))?.value;}
export async function hubRequest(who:string,route:string,body?:unknown,method?:string){const link=await hubLink(who);if(!link)throw new Error('Connect a device hub first');const c=await connection(who,link.connectionId);if(c.kind!=='hub'||c.key.length<32)throw new Error('Choose a hub connection with its issued token');const base=c.base.replace(/\/+$/,'');const url=new URL(base);const local=String(runtimeName)==='local'&&['localhost','127.0.0.1','[::1]'].includes(url.hostname);if(!local)publicHttps(base);const response=await fetch(base+route,{method:method||(body?'PUT':'GET'),redirect:'error',headers:{Authorization:'Bearer '+c.key,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(20000)});if(!response.ok){const data:any=await response.json().catch(()=>({}));throw Object.assign(new Error(redact(data.error||'Hub HTTP '+response.status,[c.key]) as string),{status:response.status});}return response.json();}
export async function connectHub(who:string,id:string,autoPull:boolean){const previous=await hubLink(who);const c=await connection(who,id);if(c.kind!=='hub'||c.key.length<32)throw new Error('Invalid device hub connection');await set(who,'sys:device-hub',{connectionId:id,autoPull:!!autoPull,revision:0,localHash:await contextHash((await rows(who)).filter(shareable))});try{const info:any=await hubRequest(who,'/v1/info');if(!info.capabilities?.includes('shared-context'))throw new Error('Upgrade this backend to Nova 0.11 for shared context');return info;}catch(e){if(previous)await set(who,'sys:device-hub',previous);else await remove(who,'sys:device-hub');throw e;}}
export async function pullHub(who:string,confirmed=false){const link=await hubLink(who);if(!link||!confirmed&&!link.autoPull)return {skipped:true};const remote=validateShared(await hubRequest(who,'/v1/context'));if(remote.revision===link.revision&&!confirmed)return remote;const local=(await rows(who)).filter(shareable);if(!confirmed&&link.localHash&&await contextHash(local)!==link.localHash)throw Object.assign(new Error('Web context has unpublished changes. Push them or explicitly review a pull first.'),{status:409});await set(who,'sys:hub-context-backup',sharedSnapshot(local,link.revision));for(const r of local)if(!remote.records.some(x=>x.id===r.id))await removeContextRecord(who,r.id);for(const r of remote.records)await putContextRecord(who,r);await set(who,'sys:device-hub',{...link,revision:remote.revision,localHash:await contextHash(remote.records)});return remote;}
export async function pushHub(who:string,confirmed:boolean){if(!confirmed)throw new Error('Confirm sending profiles, goals and notes to this backend');const link=await hubLink(who);if(!link)throw new Error('Connect a hub first');const bundle=sharedSnapshot(await rows(who),link.revision);const remote=validateShared(await hubRequest(who,'/v1/context',bundle));await set(who,'sys:device-hub',{...link,revision:remote.revision,localHash:await contextHash(remote.records)});return remote;}

export async function updateHubTrust(who:string,autoPull:boolean){const link=await hubLink(who);if(!link)throw new Error('Connect a hub first');await set(who,'sys:device-hub',{...link,autoPull});return {autoPull};}
export async function recoverHubContext(who:string,confirmed:boolean){if(!confirmed)throw new Error('Confirm recovery first');const saved=await get<SharedContext>(who,'sys:hub-context-backup');if(!saved)throw new Error('No hub recovery copy exists');const local=(await rows(who)).filter(shareable),link=await hubLink(who);let stage=(await get<{target:SharedContext;previous:SharedContext}>(who,'sys:hub-recovery-state'))?.value;if(!stage){stage={target:validateShared(saved.value),previous:sharedSnapshot(local,link?.revision||0)};await set(who,'sys:hub-recovery-state',stage);}if(link)await set(who,'sys:device-hub',{...link,autoPull:false,localHash:'recovered-local-context-needs-review'});const target=validateShared(stage.target);for(const r of local)if(!target.records.some(x=>x.id===r.id))await removeContextRecord(who,r.id);for(const r of target.records)await putContextRecord(who,r);await set(who,'sys:hub-context-backup',stage.previous);await remove(who,'sys:hub-recovery-state');return {restored:target.records.length,autoPull:false};}
