import {replyText} from '../agent/model-client';
import {get,set,cas,create,runtimeName} from './state';import {connection} from './vault';import {defaultPolicy,validatePolicy,openGateway,type GatewayPolicy,type RouteCandidate} from '../agent/gateway';import type {AgentMessage} from '../agent/types';
export async function gatewayPolicy(who:string){return (await get<GatewayPolicy>(who,'sys:model-router'))?.value||defaultPolicy;}
export async function saveGateway(who:string,input:unknown){const policy=validatePolicy(input);for(const route of policy.routes){const c=await connection(who,route.id);if(c.kind!=='model'||!c.model)throw new Error('Routes need saved model connections with model IDs');}await set(who,'sys:model-router',policy);return policy;}
export async function gatewayResponse(who:string,system:string,messages:AgentMessage[],signal:AbortSignal,stream=true){const policy=validatePolicy(await gatewayPolicy(who));const metrics=await gatewayMetrics(who);const candidates:RouteCandidate[]=[];for(const route of policy.routes){if(!route.enabled)continue;const c=await connection(who,route.id);if(c.kind!=='model')throw new Error('Gateway route is not a model');candidates.push({...route,metrics:metrics[route.id],name:c.name,config:{base:c.base,key:c.key,model:c.model||'',protocol:c.protocol||'openai',system}});}return openGateway(policy,candidates,system,messages,signal,String(runtimeName)==='local',stream,event=>observeRoute(who,event));}

export async function gatewayModel(who:string,system:string,messages:AgentMessage[],signal:AbortSignal){const routed=await gatewayResponse(who,system,messages,signal,false);const data:any=await routed.response.json();return {text:replyText(data,routed.protocol),usage:data.usage,model:routed.model};}
export async function taskConnection(who:string,id:string){if(id!=='gateway')return connection(who,id);const policy=await gatewayPolicy(who);if(!policy.routes.some(r=>r.enabled))throw new Error('Configure and enable gateway routes first');return {id:'gateway',name:'Model gateway',kind:'model' as const,base:'',key:'',model:'auto',protocol:'openai',maxCalls:20};}

export async function gatewayMetrics(who:string){return (await get<Record<string,{samples:number;latencyMs:number;failures:number}>>(who,'sys:router-metrics'))?.value||{};}
async function observeRoute(who:string,event:{id:string;latencyMs:number;failed:boolean}){for(let retry=0;retry<5;retry++){const current=await get<Record<string,{samples:number;latencyMs:number;failures:number}>>(who,'sys:router-metrics');const all={...current?.value};const old=all[event.id]||{samples:0,latencyMs:0,failures:0};all[event.id]={samples:old.samples+(event.failed?0:1),latencyMs:event.failed?old.latencyMs:old.samples?old.latencyMs*.8+event.latencyMs*.2:event.latencyMs,failures:old.failures+(event.failed?1:0)};if(current?await cas(who,'sys:router-metrics',current.stamp,all):await create(who,'sys:router-metrics',all))return;}}
