import {connection} from './vault';
export async function github(owner:string,args:Record<string,unknown>,signal:AbortSignal){const c=await connection(owner,String(args.connectionId));if(c.kind!=='github')throw new Error('Not a GitHub connection');const action=String(args.action);const request=async(path:string,method='GET',body?:unknown)=>{const response=await fetch('https://api.github.com'+path,{method,redirect:'error',signal:AbortSignal.any([signal,AbortSignal.timeout(20000)]),headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+c.key,'X-GitHub-Api-Version':'2022-11-28','Content-Type':'application/json','User-Agent':'Nova-Agent'},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw new Error('GitHub HTTP '+response.status);return response.status===204?{}:response.json();};
 if(action==='repos'){const data:any=await request('/user/repos?per_page=100&sort=updated');return {repos:data.map((r:any)=>({name:r.full_name,defaultBranch:r.default_branch,private:r.private,permissions:r.permissions})),limit:100};}
 const repo=String(args.repo||'');if(!/^[-_.a-zA-Z0-9]+\/[-_.a-zA-Z0-9]+$/.test(repo))throw new Error('Use owner/repository');const root='/repos/'+repo;
 const ref=String(args.ref||'');if(ref&&!/^[-_./a-zA-Z0-9]{1,160}$/.test(ref))throw new Error('Invalid branch');
 if(action==='branches'){const data:any=await request(root+'/branches?per_page=100');return {branches:data.map((b:any)=>({name:b.name,sha:b.commit.sha,protected:b.protected}))};}
 if(action==='read'){const path=String(args.path||'');if(!path||path.includes('..')||path.length>300)throw new Error('Invalid file path');const result:any=await request(root+'/contents/'+path.split('/').map(encodeURIComponent).join('/')+(ref?'?ref='+encodeURIComponent(ref):''));if(Array.isArray(result))return {files:result.map((r:any)=>({path:r.path,type:r.type,sha:r.sha}))};if(result.size>200000||result.encoding!=='base64')throw new Error('Use a text file under 200 KB');const content=new TextDecoder().decode(Uint8Array.from(atob(result.content.replace(/\s/g,'')),c=>c.charCodeAt(0)));return {path:result.path,sha:result.sha,content};}
 if(action==='diff'){const base=String(args.base||'main'),head=String(args.head||ref);if(!/^[-_./a-zA-Z0-9]{1,160}$/.test(base)||!/^[-_./a-zA-Z0-9]{1,160}$/.test(head))throw new Error('Invalid comparison');const result:any=await request(root+'/compare/'+encodeURIComponent(base)+'...'+encodeURIComponent(head));return {status:result.status,files:(result.files||[]).slice(0,100).map((f:any)=>({path:f.filename,status:f.status,patch:f.patch?.slice(0,20000)}))};}
 const metadata:any=await request(root);const branch=action==='pull_request'?String(args.head||''):ref;if(!/^nova\/[-_./a-zA-Z0-9]{1,140}$/.test(branch)||branch===metadata.default_branch)throw new Error('Write only to a nova/ branch, never the default branch');
 if(action==='branch'){const base=String(args.base||metadata.default_branch);const head:any=await request(root+'/git/ref/heads/'+encodeURIComponent(base));return request(root+'/git/refs','POST',{ref:'refs/heads/'+branch,sha:head.object.sha});}
 if(action==='write'){const path=String(args.path||''),content=args.content;if(!path||path.includes('..')||path.startsWith('/')||path.length>300||typeof content!=='string'||content.length>200000)throw new Error('Invalid file');const bytes=new TextEncoder().encode(content);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);return request(root+'/contents/'+path.split('/').map(encodeURIComponent).join('/'),'PUT',{message:String(args.title||'Nova: update '+path).slice(0,200),content:btoa(binary),branch,...(typeof args.sha==='string'?{sha:args.sha}:{})});}
 if(action==='pull_request'){if(typeof args.title!=='string'||!args.title.trim()||typeof args.body!=='string'||args.body.length>30000)throw new Error('Provide a title and review description');return request(root+'/pulls','POST',{title:args.title.slice(0,200),body:args.body,head:branch,base:String(args.base||metadata.default_branch),draft:true});}
 throw new Error('Unsupported GitHub action');}
