import {get,cas,create} from './state';import {fingerprint} from '../agent/operations';import type {Chat} from '../agent/chats';
import {readFile,writeFile,rename} from 'node:fs/promises';
import path from 'node:path';
import {stateDir,withLock} from './lock';
import type {AgentMessage} from '../agent/types';
function valid(id:string){if(!/^[-_a-zA-Z0-9]{1,100}$/.test(id))throw new Error('Invalid session ID');return id;}
export async function sessionMessages(id:string):Promise<AgentMessage[]>{valid(id);const shared=await get<Chat>('local','sys:chat:session-'+(await fingerprint(id)).slice(0,24));if(shared)return shared.value.messages.map(m=>({role:m.role,content:m.content}));try{const data=JSON.parse(await readFile(path.join(stateDir(),'sessions.json'),'utf8'));return data[id]||[];}catch(e){if((e as NodeJS.ErrnoException).code==='ENOENT')return [];throw e;}}
export async function appendSession(id:string,goal:string,answer:string){valid(id);await withLock('sessions',async()=>{let data:Record<string,AgentMessage[]>={};const file=path.join(stateDir(),'sessions.json');try{data=JSON.parse(await readFile(file,'utf8'));}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;}if(!data[id]&&Object.keys(data).length>=100)throw new Error('Session limit reached');data[id]=[...(data[id]||[]),{role:'user',content:goal.slice(0,10000)},{role:'assistant',content:answer.slice(0,10000)}].slice(-20) as AgentMessage[];const tmp=file+'.'+crypto.randomUUID()+'.tmp';await writeFile(tmp,JSON.stringify(data),{mode:0o600});await rename(tmp,file);const chatId='session-'+(await fingerprint(id)).slice(0,24);const user={id:crypto.randomUUID(),role:'user' as const,content:goal.slice(0,10000)},assistant={id:crypto.randomUUID(),role:'assistant' as const,content:answer.slice(0,10000)};let saved=false;for(let attempt=0;attempt<5;attempt++){const existing=await get<Chat>('local','sys:chat:'+chatId);const chat={id:chatId,title:existing?.value.title||'Session: '+id,messages:[...(existing?.value.messages||[]),user,assistant].slice(-300),updatedAt:Date.now()};if(existing?await cas('local','sys:chat:'+chatId,existing.stamp,chat):await create('local','sys:chat:'+chatId,chat)){saved=true;break;}}if(!saved)throw new Error('Session changed concurrently; retry delivery');});}
/** Only trusted environment mappings can link sender identities to the same session. */
export function linkedSession(channel:string,sender:string){const links:Record<string,string>=JSON.parse(process.env.NOVA_GATEWAY_LINKS||'{}');return links[channel+':'+sender]?valid(links[channel+':'+sender]):undefined;}
