import {get,set,cas,create,rows,runtimeName} from './state';
import {connections} from './vault';
import {voiceSettings} from './voice';
import {hubLink} from './device-hub';
import {runnerToken} from './runner-token';
export type ModelLimits={dailyCalls:number};
export async function modelLimits(who:string):Promise<ModelLimits>{return (await get<ModelLimits>(who,'sys:model-limits'))?.value||{dailyCalls:0};}
export async function saveLimits(who:string,input:any){if(!input||!Number.isInteger(input.dailyCalls)||input.dailyCalls<0||input.dailyCalls>100000)throw new Error('Daily calls must be a whole number from 0 to 100,000');await set(who,'sys:model-limits',{dailyCalls:input.dailyCalls});return modelLimits(who);}
type Usage={day:string;calls:number;failures:number;lastLatencyMs?:number;updatedAt:number};
const today=()=>new Date().toISOString().slice(0,10);
export async function modelUsage(who:string){const value=(await get<Usage>(who,'sys:model-usage'))?.value;return value?.day===today()?value:{day:today(),calls:0,failures:0,updatedAt:Date.now()};}
export async function reserveModelCall(who:string){for(let retry=0;retry<12;retry++){const old=await get<Usage>(who,'sys:model-usage'),usage=old?.value.day===today()?old.value:{day:today(),calls:0,failures:0,updatedAt:Date.now()},limits=await modelLimits(who);if(limits.dailyCalls&&usage.calls>=limits.dailyCalls)throw Object.assign(new Error('Daily model call limit reached. Adjust it in Settings → Setup.'),{status:429});const next={...usage,calls:usage.calls+1,updatedAt:Date.now()};if(old?await cas(who,'sys:model-usage',old.stamp,next):await create(who,'sys:model-usage',next))return;}throw Object.assign(new Error('Usage counter busy; retry shortly'),{status:409});}
export async function finishModelCall(who:string,failed:boolean,latencyMs:number){for(let retry=0;retry<12;retry++){const old=await get<Usage>(who,'sys:model-usage');if(!old||old.value.day!==today())return;const next={...old.value,failures:old.value.failures+(failed?1:0),lastLatencyMs:latencyMs,updatedAt:Date.now()};if(await cas(who,'sys:model-usage',old.stamp,next))return;}}
export async function metered<T>(who:string,fn:()=>Promise<T>):Promise<T>{await reserveModelCall(who);const at=Date.now();let failed=true;try{const result=await fn();failed=false;return result;}finally{await finishModelCall(who,failed,Date.now()-at);}}
export async function settingsOverview(who:string){const saved=await connections(who),voice=await voiceSettings(who),hub=await hubLink(who),all=await rows(who),tasks=all.filter(r=>r.id.startsWith('sys:task:')).map(r=>JSON.parse(r.content));return {runtime:runtimeName,storage:String(runtimeName)==='local'?'Local workspace files':'Managed D1 database',connections:saved,voice:{output:voice.output,connectionId:voice.connectionId,preset:'Irish spark'},hub:hub?{revision:hub.revision,autoPull:hub.autoPull}:null,limits:await modelLimits(who),usage:await modelUsage(who),queue:{queued:tasks.filter(t=>t.status==='queued').length,running:tasks.filter(t=>t.status==='running').length,failed:tasks.filter(t=>t.status==='failed').length,expiredLeases:tasks.filter(t=>t.status==='running'&&(t.leaseUntil||0)<Date.now()).length},runner:{configured:runnerToken().length>=32},memory:{notes:all.filter(r=>r.kind==='memory').length,hasRecoveryCopy:all.some(r=>r.id==='sys:hub-context-backup')}};}
