import {gatewayModel,taskConnection} from './gateway';
import {auditRecord} from '../agent/approval';import {checkPermission} from '../agent/operations';
import {saveRecord} from './local-workspace';
import {get,set,rows,cas,runtimeName} from './state';
import {connection} from './vault';import {NovaCore} from '../agent/core';import {requestModel} from '../agent/model-client';import {readUrl} from '../agent/http';import {service} from './service';import {validateRecord} from '../agent/records';import {parseSchedule,nextOccurrence,type Schedule} from '../agent/schedule';import type {AgentRun} from '../agent/types';
export type Task={id:string;goal:string;connectionId:string;status:'queued'|'running'|'completed'|'failed'|'cancelled';run?:AgentRun;calls:number;tokens:number;maxCalls:number;maxTokens:number;nextAt:number;leaseUntil?:number;lease?:string;error?:string;schedule?:Schedule;workspace:boolean;createdAt:number;updatedAt:number};
export async function tasks(who:string){return (await rows(who)).filter(r=>r.id.startsWith('sys:task:')).map(r=>JSON.parse(r.content) as Task).sort((a,b)=>b.createdAt-a.createdAt);}
export async function createTask(who:string,input:any){if(typeof input.goal!=='string'||!input.goal.trim()||input.goal.length>12000)throw new Error('Supply a goal under 12,000 characters');if(input.workspace===true)checkPermission({name:'write_file',args:{}},(process.env.NOVA_PERMISSION_LEVEL||'operator') as any);const config=await taskConnection(who,String(input.connectionId));if(config.kind!=='model'||!config.model)throw new Error('Choose a saved model connection');if((await tasks(who)).filter(t=>['queued','running'].includes(t.status)).length>=20)throw new Error('Twenty active tasks already exist');const schedule=input.scheduleText?parseSchedule(String(input.scheduleText),String(input.timezone||'UTC')):undefined;const now=Date.now();const task:Task={id:crypto.randomUUID(),goal:input.goal.trim(),connectionId:config.id,status:'queued',calls:0,tokens:0,maxCalls:Math.min(40,Math.max(2,Number(input.maxCalls)||config.maxCalls||20)),maxTokens:Math.min(200000,Math.max(1000,Number(input.maxTokens)||40000)),nextAt:schedule?nextOccurrence(schedule):now,schedule,workspace:input.workspace===true,createdAt:now,updatedAt:now};await set(who,'sys:task:'+task.id,task);return task;}
export async function cancelTask(who:string,id:string){for(let i=0;i<3;i++){const old=await get<Task>(who,'sys:task:'+id);if(!old)throw new Error('Task not found');if(await cas(who,'sys:task:'+id,old.stamp,{...old.value,status:'cancelled',updatedAt:Date.now()}))return;}throw new Error('Concurrent task change; retry');}
export async function tick(who:string,onlyId?:string,outer?:AbortSignal){const due=(await tasks(who)).filter(t=>(!onlyId||t.id===onlyId)&&t.nextAt<=Date.now()&&(t.status==='queued'||t.status==='running'&&(t.leaseUntil||0)<Date.now())).slice(0,2);await Promise.allSettled(due.map(t=>runTask(who,t.id,outer)));return {checked:due.length};}
export async function runTask(who:string,id:string,outer?:AbortSignal){const key='sys:task:'+id;let record=await get<Task>(who,key);if(!record||record.value.nextAt>Date.now()||!['queued','running'].includes(record.value.status)||record.value.status==='running'&&(record.value.leaseUntil||0)>Date.now())return;let task:Task={...record.value,status:'running',lease:crypto.randomUUID(),leaseUntil:Date.now()+120000,updatedAt:Date.now()};if(!await cas(who,key,record.stamp,task))return;const lease=task.lease;const abort=new AbortController();const cancel=()=>abort.abort(outer?.reason);if(outer?.aborted)cancel();else outer?.addEventListener('abort',cancel,{once:true});const deadline=setTimeout(()=>abort.abort(new Error('Checkpoint time slice ended')),String(runtimeName)==='web'?26000:120000);
const commit=async()=>{const latest=await get<Task>(who,key);if(!latest||latest.value.status==='cancelled'||latest.value.lease!==lease){abort.abort(new Error('Task cancelled or reclaimed'));throw new Error('Task cancelled or reclaimed');}if(!await cas(who,key,latest.stamp,task))throw new Error('Task checkpoint conflict');};
let saves=Promise.resolve();const checkpoint=(run:AgentRun)=>{task={...task,run:structuredClone(run),updatedAt:Date.now()};saves=saves.then(commit).catch(e=>{abort.abort(e);});};
try{if(task.workspace)checkPermission({name:'write_file',args:{}},(process.env.NOVA_PERMISSION_LEVEL||'operator') as any);const config=await taskConnection(who,task.connectionId);const baseRun:AgentRun=task.run||{id:crypto.randomUUID(),goal:task.goal,status:'running',plan:[],events:[],transcript:[{role:'user',content:task.goal}],answer:'',updatedAt:Date.now()};if(task.run)baseRun.transcript.push({role:'user',content:'Resume from the persisted checkpoint. Inspect state before repeating an interrupted operation.'});
const allowed=['list_connections','list_files','read_file','search_memory','fetch_url','calculate','search_documents','search_history','search_web','verify_file','delegate',...(task.workspace?['write_file','save_memory','save_skill']:[])];
const core=new NovaCore({audit:async entry=>{await saveRecord(await auditRecord(entry,'background-core'));},listRecords:async()=>({records:(await rows(who)).filter(r=>!r.id.startsWith('sys:')&&!r.id.startsWith('approval:')) as any}),saveRecord:async record=>{const valid=validateRecord(record);return saveRecord(valid);},fetchUrl:readUrl,service:(call,signal)=>service(who,call,signal),model:async(system,messages,signal)=>{await saves;signal.throwIfAborted();if(task.calls>=task.maxCalls||task.tokens>=task.maxTokens)throw new Error('Task model budget reached');task.calls++;await commit();const reply=task.connectionId==='gateway'?await gatewayModel(who,system,messages,signal):await requestModel(config as any,system,messages,signal,String(runtimeName)==='local');task.tokens+=Number(reply.usage?.total_tokens||Number(reply.usage?.input_tokens||0)+Number(reply.usage?.output_tokens||0)||Math.ceil((system.length+messages.reduce((n,m)=>n+m.content.length,0)+reply.text.length)/4));await commit();return reply;}},{runtime:runtimeName,terminalEnabled:false},{level:task.workspace?'workspace':'read',allowedTools:allowed,immutableFiles:['soul.md','user.md']},[config.key]);
const result=await core.run({run:baseRun,persona:'Perform the queued goal. No sensitive actions are preapproved. Finish with evidence and any unmet criteria.',maxSteps:Math.max(2,task.maxCalls-task.calls),signal:abort.signal,update:checkpoint,persist:task.workspace});await saves;task.run=result;task.status=result.status==='completed'?'completed':result.status==='paused'&&task.calls<task.maxCalls&&task.tokens<task.maxTokens?'queued':'failed';task.error=task.status==='failed'?result.answer:undefined;
if(task.status==='completed'&&task.schedule){task={...task,status:'queued',run:undefined,calls:0,tokens:0,nextAt:nextOccurrence(task.schedule)};await set(who,'run:'+result.id,{...result});}
}catch(e){task.status=abort.signal.aborted&&task.calls<task.maxCalls?'queued':'failed';task.error=(e as Error).message;}finally{clearTimeout(deadline);outer?.removeEventListener('abort',cancel);task.leaseUntil=0;task.updatedAt=Date.now();await saves.catch(()=>{});await commit().catch(()=>{});}}
