import test from 'node:test';
import assert from 'node:assert/strict';
import {loadTs} from './load-ts.mjs';
import {mkdtemp,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
const {parseSchedule,nextOccurrence}=await loadTs('../lib/agent/schedule.ts');
const {synthesize}=await loadTs('../lib/agent/synthesis.ts');
const {parseSkill,executeSkill}=await loadTs('../lib/agent/framework.ts');
const {NovaCore}=await loadTs('../lib/agent/core.ts');
const run=goal=>({id:crypto.randomUUID(),goal,status:'running',plan:[],events:[],transcript:[{role:'user',content:goal}],answer:'',updatedAt:Date.now()});
test('calendar scheduler validates phrases and computes timezone and DST occurrences',()=>{
 const daily=parseSchedule('every morning at 8 AM','Asia/Kolkata');assert.equal(new Date(nextOccurrence(daily,Date.parse('2026-10-07T01:00Z'))).toISOString(),'2026-10-07T02:30:00.000Z');
 const weekly=parseSchedule('every Monday at 18:30','UTC');assert.equal(new Date(nextOccurrence(weekly,Date.parse('2026-10-07T01:00Z'))).toISOString(),'2026-10-12T18:30:00.000Z');
 const dst=parseSchedule('daily at 1:30 AM','America/New_York');assert.equal(new Date(nextOccurrence(dst,Date.parse('2026-11-01T05:30Z'))).toISOString(),'2026-11-02T06:30:00.000Z');
 assert.throws(()=>parseSchedule('every morning at 25:90','UTC'));assert.throws(()=>parseSchedule('every 1 minute','UTC'));assert.throws(()=>parseSchedule('whenever convenient','UTC'));assert.throws(()=>parseSchedule('daily at 8','Fake/Zone'));
});
test('synthesis stores portable parameterized procedure without task literals and tracks evidence',async()=>{
 const calls=[{name:'read_file',args:{path:'private-secret.txt'}},{name:'fetch_url',args:{url:'https://example.org/private?q=secret'}},{name:'calculate',args:{expression:'123+456'}}];
 const records=await synthesize(calls,[],'run-one');assert.equal(records.length,3);assert.ok(records.some(r=>r.name.endsWith('/SKILL.md')));assert.ok(!JSON.stringify(records).includes('private-secret'));assert.ok(!JSON.stringify(records).includes('123+456'));
 const skill=parseSkill(records[0].content),executed=[];await assert.rejects(executeSkill(skill,async()=>{},new AbortController().signal),/parameter/);
 const params=Object.fromEntries(skill.parameters.map(k=>[k,'fresh-value']));await executeSkill(skill,async c=>{executed.push(c);return {ok:true};},new AbortController().signal,params);assert.equal(executed[0].args.path,'fresh-value');
 const again=await synthesize(calls,records,'run-two');assert.equal(JSON.parse(again[0].content).evidenceCount,2);assert.equal(again.length,2);assert.deepEqual(await synthesize([...calls,{name:'run_command',args:{command:'secret'}}],[],'r'),[]);
});
test('child agents overlap, preserve structured lineage, and cannot mutate parent workspace',async()=>{
 let active=0,peak=0;const records=[],events=[];
 const core=new NovaCore({listRecords:async()=>({records}),saveRecord:async r=>{records.push(r);return r;},fetchUrl:async()=>({}),audit:async e=>events.push(e),model:async(system,messages)=>{active++;peak=Math.max(peak,active);await new Promise(r=>setTimeout(r,15));active--;return JSON.stringify({type:'final',answer:'Evidence for '+messages[0].content});}},{runtime:'local',terminalEnabled:false},{level:'read'});
 const results=await core.execute({name:'delegate',args:{tasks:['one','two','three']}},new AbortController().signal);assert.equal(peak,3);assert.equal(results.results.length,3);assert.equal(new Set(results.results.map(r=>r.childId)).size,3);assert.ok(results.results.every(r=>r.status==='completed'));assert.equal(records.length,0);
 await assert.rejects(core.execute({name:'delegate',args:{tasks:['1','2','3','4']}},new AbortController().signal));
 let calls=0;const childCore=new NovaCore({listRecords:async()=>({records:[]}),saveRecord:async()=>{throw new Error('unexpected mutation');},fetchUrl:async()=>({}),model:async()=>JSON.stringify(++calls===1?{type:'tool',name:'write_file',args:{path:'p.txt',content:'bad'}}:{type:'final',answer:'Denied'})},{runtime:'web',terminalEnabled:false},{level:'read'});const denied=await childCore.execute({name:'delegate',args:{tasks:['write']}},new AbortController().signal);assert.equal(denied.results[0].status,'completed');
});
test('automatic skill capture runs only for completed workflows with save permission',async()=>{
 const records=[];let calls=0;const core=new NovaCore({listRecords:async()=>({records}),saveRecord:async r=>{const i=records.findIndex(x=>x.id===r.id);if(i>=0)records[i]=r;else records.push(r);return r;},fetchUrl:async()=>({}),model:async()=>JSON.stringify(++calls<=3?{type:'tool',name:'calculate',args:{expression:String(calls)+'+1'}}:{type:'final',answer:'Done'})},{runtime:'web',terminalEnabled:false},{level:'workspace'});await core.run({run:run('calculate'),persona:'',maxSteps:6,signal:new AbortController().signal,update:()=>{}});assert.ok(records.some(r=>r.name.endsWith('/SKILL.md')));
});
test('trusted mappings link sessions and transcripts survive reload',async()=>{const tmp=await mkdtemp(path.join(os.tmpdir(),'nova-session-'));const old=process.env.NOVA_STATE_DIR;process.env.NOVA_STATE_DIR=tmp;try{const {appendSession,sessionMessages,linkedSession}=await loadTs('../lib/server/sessions.ts');process.env.NOVA_GATEWAY_LINKS='{"telegram:123":"personal","discord:abc":"personal"}';assert.equal(linkedSession('telegram','123'),linkedSession('discord','abc'));assert.equal(linkedSession('telegram','unknown'),undefined);await appendSession('personal','goal','answer');assert.equal((await sessionMessages('personal')).length,2);await assert.rejects(sessionMessages('../secret'));}finally{if(old===undefined)delete process.env.NOVA_STATE_DIR;else process.env.NOVA_STATE_DIR=old;delete process.env.NOVA_GATEWAY_LINKS;await rm(tmp,{recursive:true,force:true});}});
test('revised skills retain old procedure snapshots and increment versions',async()=>{const records=[];const core=new NovaCore({listRecords:async()=>({records}),saveRecord:async r=>{const i=records.findIndex(x=>x.id===r.id);if(i>=0)records[i]=r;else records.push(r);return r;},fetchUrl:async()=>({}),model:async()=>''},{runtime:'web',terminalEnabled:false},{level:'workspace'});const first={name:'routine',description:'initial',steps:[{name:'calculate',args:{expression:'1+1'}}]};assert.equal((await core.execute({name:'save_skill',args:first},new AbortController().signal)).version,1);const v1=records.find(r=>r.name.endsWith('/v1.SKILL.md')).content;assert.equal((await core.execute({name:'save_skill',args:{...first,description:'revised'}},new AbortController().signal)).version,2);assert.equal(records.find(r=>r.name.endsWith('/v1.SKILL.md')).content,v1);assert.ok(records.find(r=>r.name.endsWith('/v2.SKILL.md')));});
test('delegated cancellation waits for children and denies mutation before side effects',async()=>{let saves=0;const observed=[];const core=new NovaCore({listRecords:async()=>({records:[]}),saveRecord:async()=>{saves++;throw new Error('unexpected');},fetchUrl:async()=>({}),model:async(system,messages,signal)=>{if(messages.length===1)return JSON.stringify({type:'tool',name:'write_file',args:{path:'unauthorized.txt',content:'bad'}});observed.push(messages.at(-1).content);return JSON.stringify({type:'final',answer:'No change made'});}},{runtime:'local',terminalEnabled:true},{level:'operator'});const result=await core.execute({name:'delegate',args:{tasks:['one','two']}},new AbortController().signal);assert.equal(saves,0);assert.ok(observed.every(v=>v.includes('Tool not permitted: write_file')));assert.equal(result.results.length,2);
 const abort=new AbortController();let finished=0;const cancelling=new NovaCore({listRecords:async()=>({records:[]}),saveRecord:async()=>{throw new Error('unexpected');},fetchUrl:async()=>({}),model:async(system,messages,signal)=>{await new Promise((resolve,reject)=>{signal.addEventListener('abort',()=>setTimeout(()=>{finished++;reject(new DOMException('cancelled','AbortError'));},10),{once:true});});return ''; }},{runtime:'web',terminalEnabled:false},{level:'read'});const pending=cancelling.execute({name:'delegate',args:{tasks:['one','two']}},abort.signal);setTimeout(()=>abort.abort(),15);await assert.rejects(pending);assert.equal(finished,2);
});

test('draft delegation keeps changes isolated and returns proposals for parent review',async()=>{const parent=[{id:'file:report.md',kind:'file',name:'report.md',content:'original',updatedAt:1}];let calls=0,saves=0;const core=new NovaCore({listRecords:async()=>({records:parent}),saveRecord:async()=>{saves++;throw new Error('parent write unexpected');},fetchUrl:async()=>({}),model:async()=>JSON.stringify(++calls===1?{type:'tool',name:'write_file',args:{path:'report.md',content:'proposal'}}:{type:'final',answer:'Draft ready'})},{runtime:'local',terminalEnabled:false},{level:'workspace'});const result=await core.execute({name:'delegate',args:{tasks:['draft a change'],mode:'draft'}},new AbortController().signal);assert.equal(result.results[0].patches[0].content,'proposal');assert.equal(parent[0].content,'original');assert.equal(saves,0);});
