import {linkedSession} from '../../../lib/server/sessions';
import { timingSafeEqual, createHash } from 'node:crypto';
import { localRequest } from '../../../lib/server/local-workspace';
import { sameOrigin } from '../../../lib/agent/http';
import { jobState, mutateJobs, newJob } from '../../../lib/server/jobs';
export const runtime='nodejs';
function authorized(req:Request){const token=process.env.NOVA_GATEWAY_TOKEN;if(!token||!localRequest(req)||!sameOrigin(req))return false;const supplied=req.headers.get('authorization')||'';return timingSafeEqual(createHash('sha256').update(supplied).digest(),createHash('sha256').update('Bearer '+token).digest());}
export async function POST(req:Request){if(!authorized(req))return Response.json({error:'Gateway authorization required'},{status:401});try{const {goal,requestId,channel,sender}=await req.json();const sessionId=channel&&sender?linkedSession(String(channel),String(sender)):undefined;if((channel||sender)&&!sessionId)throw new Error('Sender identity must be configured in NOVA_GATEWAY_LINKS');if(typeof requestId!=='string'||!/^[-_a-zA-Z0-9]{1,120}$/.test(requestId))throw new Error('Use a stable requestId (letters, numbers, dash, underscore).');const job=await mutateJobs(state=>{const existing=state.jobs.find(j=>j.requestId===requestId);if(existing){if(existing.goal!==goal)throw new Error('requestId is already used for a different goal');return existing;}if(state.jobs.length>=100)throw new Error('Job limit reached');const next=newJob({goal,allowedTools:(process.env.NOVA_GATEWAY_TOOLS||'list_files,read_file,search_memory,fetch_url,calculate').split(',').map(t=>t.trim()).filter(Boolean),commands:[],notify:false});next.requestId=requestId;next.sessionId=sessionId;state.jobs.push(next);return next;});return Response.json({jobId:job.id,status:job.status});}catch(e){return Response.json({error:(e as Error).message},{status:400});}}
export async function GET(req:Request){if(!authorized(req))return Response.json({error:'Gateway authorization required'},{status:401});const id=new URL(req.url).searchParams.get('jobId');const job=(await jobState()).jobs.find(j=>j.id===id);if(!job)return Response.json({error:'Job not found'},{status:404});return Response.json({jobId:job.id,status:job.status,result:job.result,runId:job.runId});}
