import {setupWizard,verifyBackend,pairDevice} from './setup';
import {deviceDoctor} from './doctor';
import {loadDeviceGateway} from './router';
import {createInterface} from 'node:readline/promises';import {stdin,stdout,stderr} from 'node:process';import path from 'node:path';import {createHash} from 'node:crypto';import {BackendClient} from './coding/remote';import {backendUrl,remoteConfig,saveConfig,loadConfig} from './coding/config';import {DeviceStore,type CodingSession} from './coding/store';import {ProjectFiles,projectRoot,clean} from './coding/files';import {runCodingTurn} from './coding/runner';import {startBackend} from './coding/backend';
const HELP=`Nova Code CLI 0.13.0

nova setup backend|local|connect             Guided configuration with hidden key entry
nova connect https://your-backend.example    Connect and save a scoped backend token
nova                                        Interactive coding chat in this project
nova -p "Review this code" --plan             Read-only one-shot / piped context
nova --continue                             Continue the newest project session
nova resume SESSION_ID                      Resume a local or cloud session
nova sessions                               List project sessions
nova live                                   Watch live session snapshots
nova steer SESSION_ID TEXT                  Queue guidance for the active session
nova stop SESSION_ID                        Request a stop on its running device
nova extensions list|install PATH|remove ID  Review portable skill extensions
nova models                                 Show allowed backend models
nova context pull|push                      Sync shared goals, profiles and notes
nova context-session SESSION_ID             Import a hub conversation into this project
nova verify                                 Test one real model decision through the backend
nova doctor                                 Check backend and project connection
nova backend                                Start the deployable backend
nova pair URL                               Pair this device using a hidden one-use code
nova devices list|pair LABEL|revoke ID       Administer your paired device tokens
nova backend-health                         Inspect usage, queue and audit summary
nova backend-backup                         Create a protected SQLite snapshot on the host

--project PATH         Project root (defaults to current directory)
--project-id NAME      Stable identity for the same repo on multiple devices
--backend URL          Override URL; token must match that backend
--scopes LIST          Pairing scopes, comma separated (default all device scopes)
--execution MODE       docker (default), native (explicit host commands), none
--plan                 Read-only planning mode
--model ID             Choose an allowed backend model
--max-steps 2..40       Agent decision limit (default 20)
--json                 One-shot structured result; all logs go to stderr
--direct               Use NOVA_MODEL_* locally instead of a Nova backend
--help / --version

Interactive: /help /plan /code /diff /status /undo /new /retry /sessions /model ID /exit
Model provider keys stay on the backend. Local code/tool results sent for inference
are visible to that backend. All edits and commands require interactive approval.
`;
function argsOf(argv:string[]){const out:any={_:[]};const values=new Set(['project','project-id','backend','execution','max-steps','model','resume','p','print','scopes']);const bool=new Set(['help','version','plan','json','direct','continue']);for(let i=0;i<argv.length;i++){const arg=argv[i];if(!arg.startsWith('-')){out._.push(arg);continue;}const [name,inline]=arg.replace(/^--?/,'').split('=',2);if(values.has(name)){const value=inline??argv[++i];if(value===undefined||value.startsWith('--'))throw new Error('Missing value for --'+name);out[name]=value;}else if(bool.has(name)){if(inline)throw new Error('--'+name+' does not take a value');out[name]=true;}else throw new Error('Unknown option '+arg);}return out;}
async function pipeInput(){let text='',bytes=0;for await(const part of stdin){bytes+=part.length;if(bytes>60000)throw new Error('Piped context exceeds 60 KB');text+=part.toString();}return text;}
export async function main(argv=process.argv.slice(2)){const args=argsOf(argv);if(args.help){stdout.write(HELP);return;}if(args.version){stdout.write('0.13.0\n');return;}if(args._[0]==='setup'){await setupWizard(args._[1]||'connect',path.resolve(args.project||process.cwd()));return;}if(args._[0]==='verify'){stdout.write(JSON.stringify(await verifyBackend(await remoteConfig(args.backend)),null,2)+'\n');return;}if(args._[0]==='backend'){await startBackend();return;}if(args._[0]==='pair'){stdout.write(JSON.stringify(await pairDevice(args._[1]||args.backend||'',process.env.NOVA_PAIR_CODE),null,2)+'\n');return;}if(['devices','backend-health','backend-backup'].includes(args._[0])){const client=new BackendClient(await remoteConfig(args.backend));let route='/v1/admin/health',options:RequestInit={};if(args._[0]==='backend-backup'){route='/v1/admin/backup';options={method:'POST'};}if(args._[0]==='devices'){const action=args._[1];if(action==='list')route='/v1/admin/devices';else if(action==='pair'){route='/v1/admin/pair';options={method:'POST',body:JSON.stringify({label:args._[2],scopes:args.scopes?args.scopes.split(','):undefined})};}else if(action==='revoke'){route='/v1/admin/revoke';options={method:'POST',body:JSON.stringify({id:args._[2]})};}else throw new Error('Use nova devices list, nova devices pair LABEL or nova devices revoke ID');}stdout.write(JSON.stringify(await(await client.request(route,options)).json(),null,2)+'\n');return;}if(args._[0]==='connect'){const backend=backendUrl(args._[1]||args.backend||'');const token=process.env.NOVA_BACKEND_TOKEN||'';if(token.length<32)throw new Error('Set NOVA_BACKEND_TOKEN to the backend-issued token before connecting (never put it in a command argument)');const client=new BackendClient({backend,token});const info=await client.info();await saveConfig({backend,token});stdout.write('Connected to '+backend+' · '+info.model+'\nToken saved with owner-only file permissions.\n');return;}
if(args._[0]==='extensions'){const {SkillExtensions}=await import('./coding/extensions');const registry=new SkillExtensions();const action=args._[1];if(action==='list')stdout.write(JSON.stringify(await registry.list(),null,2)+'\n');else if(action==='install'){if(!stdin.isTTY)throw new Error('Extension installation requires interactive review');const bundle=await registry.inspect(args._[2]);stdout.write(JSON.stringify(bundle.summary,null,2)+'\n');const rl=createInterface({input:stdin,output:stdout});try{if((await rl.question('Install these reviewed skill templates? [yes/no] ')).trim().toLowerCase()==='yes')await registry.install(bundle);}finally{rl.close();}}else if(action==='remove'){await registry.remove(args._[2]);stdout.write('Extension removed.\n');}else throw new Error('Use extensions list, install PATH, or remove ID');return;}
if(['live','steer','stop'].includes(args._[0])){const client=new BackendClient(await remoteConfig(args.backend));stdout.write(JSON.stringify(args._[0]==='live'?await client.live():await client.control(args._[1],args._[0]==='stop'?'stop':'steer',args._.slice(2).join(' ')),null,2)+'\n');return;}
const root=await projectRoot(path.resolve(args.project||process.cwd()));const projectId=createHash('sha256').update(args['project-id']||root).digest('hex').slice(0,32),store=new DeviceStore(projectId);let backend:BackendClient|undefined;if(!args.direct){try{backend=new BackendClient(await remoteConfig(args.backend));}catch(e){if(args._[0]!=='doctor')throw e;}}const log=(text:string)=>(args.json?stderr:stdout).write(clean(text)+'\n');
const directGateway=args.direct?await loadDeviceGateway():undefined;if(args.model){if(directGateway)process.env.NOVA_ROUTE=args.model;else if(backend)backend.model=args.model;else process.env.NOVA_MODEL=args.model;}if(args._[0]==='models'){log(JSON.stringify(backend?(await backend.info()).models:directGateway?['auto',...directGateway.candidates.filter(r=>r.enabled).map(r=>'route:'+r.id)]:[process.env.NOVA_MODEL],null,2));return;}
if(args._[0]==='doctor'){let info;try{info=backend?await backend.info():{model:directGateway?'auto':process.env.NOVA_MODEL,mode:args.direct?'direct':'not connected',routing:directGateway?.policy.mode};}catch(e){info={connectionError:(e as Error).message};}const localRoutes=directGateway?.candidates||(process.env.NOVA_MODEL_BASE&&process.env.NOVA_MODEL?[{id:'configured-model',role:'general' as const,priority:50,enabled:true,config:{base:process.env.NOVA_MODEL_BASE,key:process.env.NOVA_MODEL_KEY||'',model:process.env.NOVA_MODEL,protocol:process.env.NOVA_MODEL_PROTOCOL||'openai',system:''}}]:[]);log(JSON.stringify({...info,diagnostics:await deviceDoctor(localRoutes),project:root,execution:args.execution||'docker',token:backend?'configured; not displayed':'not configured'},null,2));return;}
const execution=args.execution||'docker';if(!['docker','native','none'].includes(execution))throw new Error('Use --execution docker, native, or none');const maxSteps=Number(args['max-steps']||20);if(!Number.isInteger(maxSteps)||maxSteps<2||maxSteps>40)throw new Error('--max-steps must be 2..40');
if(args._[0]==='sessions'){const sessions=await store.list();for(const s of sessions)log(s.id+' · '+s.title+' · '+new Date(s.updatedAt).toLocaleString());if(backend){try{for(const s of (await backend.list(projectId)).sessions)if(!sessions.some(local=>local.id===s.id))log(s.id+' · '+s.title+' · cloud');}catch(e){log('Cloud list: '+(e as Error).message);}}return;}
if(args._[0]==='context-session'){if(!backend)throw new Error('A backend is required');const release=await store.lock();try{const saved=await backend.load(args._[1]);if(!saved?.session)throw new Error('Session not found');const copy:CodingSession={id:crypto.randomUUID(),projectId,title:saved.session.title,messages:saved.session.messages,updatedAt:Date.now()};await store.save(copy);log('Imported conversation. Continue with nova resume '+copy.id);}finally{await release();}return;}
if(args._[0]==='context'){const unlockContext=await store.lock();try{if(!backend)throw new Error('Context sync needs a configured backend');const {validateShared,sharedSnapshot}=await import('../lib/agent/shared-context');if(args._[1]==='pull'){await store.saveShared(validateShared(await backend.context()));log('Shared context loaded outside your project. Local project profiles take priority.');return;}if(args._[1]==='push'){if(!stdin.isTTY)throw new Error('Context push requires interactive review');const rl=createInterface({input:stdin,output:stdout});try{const shared=await store.shared();const f=new ProjectFiles(root,store,async()=>false);const snapshot=sharedSnapshot((await f.records()).records,shared?.revision||0);log('Send these profiles/notes to your backend: '+snapshot.records.map(r=>r.name).join(', '));if((await rl.question('Approve shared context upload? [yes/no] ')).trim().toLowerCase()!=='yes')return;await store.saveShared(validateShared(await backend.saveContext(snapshot)));log('Shared context saved.');}finally{rl.close();}return;}throw new Error('Use nova context pull or nova context push');}finally{await unlockContext();}}const release=await store.lock();let input:ReturnType<typeof createInterface>|undefined;let active:AbortController|undefined,closed=false;let plan=args.plan||!stdin.isTTY;const confirm=async(description:string,signal:AbortSignal)=>{if(!stdin.isTTY||!input)return false;signal.throwIfAborted();log('\n'+description);return (await input.question('Approve this exact action? [yes/no] ',{signal})).trim().toLowerCase()==='yes';};const files=new ProjectFiles(root,store,confirm);
const newSession=():CodingSession=>({id:crypto.randomUUID(),projectId,title:'New coding session',messages:[],updatedAt:Date.now()});let session:CodingSession=newSession();let requested=args.resume||(args._[0]==='resume'?args._[1]:undefined);if(args.continue)requested=(await store.list())[0]?.id;
try{if(requested){session=await store.load(requested)||((await backend?.load(requested))?.session as CodingSession);if(!session)throw new Error('Session not found');if(session.projectId!==projectId)throw new Error('Session belongs to a different project. Use the same --project-id or choose its original project.');}
if(stdin.isTTY){input=createInterface({input:stdin,output:stdout});input.on('close',()=>{closed=true;active?.abort();});input.on('SIGINT',()=>{if(active)active.abort();else input?.close();});}const interrupt=()=>{if(active)active.abort();else{closed=true;input?.close();}};process.on('SIGINT',interrupt);
try{if(backend)await backend.info();log('Nova Code · '+root+'\nSession '+session.id+' · '+(plan?'plan mode':'reviewed edits')+' · '+execution+' commands');if(execution==='native')log('Native mode: approved commands run with your device permissions; this is not a sandbox.');let prompt=args.p||args.print||(args._[0]==='resume'?'':args._.join(' '));if(!stdin.isTTY){const context=await pipeInput();if(context)prompt+=(prompt?'\n\nPIPED CONTEXT:\n':'')+context;if(!prompt.trim())throw new Error('Pass -p "your task" or pipe a prompt');}
let retryNext=false;let once=!!(args.p||args.print)||!stdin.isTTY;while(!closed){if(!prompt)prompt=await input!.question('You: ');if(!prompt.trim()){prompt='';continue;}if(prompt.startsWith('/')){const command=prompt.trim();prompt='';if(['/exit','/quit'].includes(command))break;if(command==='/help'){log(HELP);continue;}if(command==='/plan'){plan=true;log('Plan mode enabled.');continue;}if(command==='/code'){plan=false;log('Reviewed edit mode enabled.');continue;}if(command.startsWith('/model')){const selected=command.slice(6).trim();if(!backend){if(selected){if(directGateway)process.env.NOVA_ROUTE=selected;else process.env.NOVA_MODEL=selected;}log('Direct model: '+(directGateway?process.env.NOVA_ROUTE||'auto':process.env.NOVA_MODEL));}else{const info=await backend.info();if(selected){if(!info.models.includes(selected)){log('Model is not allowed by this backend.');continue;}backend.model=selected;}log('Model: '+(backend.model||info.model)+' · available '+info.models.join(', '));}continue;}if(command==='/new'){session=newSession();log('Session '+session.id);continue;}if(command==='/sessions'){for(const s of await store.list())log(s.id+' · '+s.title);continue;}if(command==='/diff'||command==='/status'){try{log(JSON.stringify(await files.git(command==='/diff'?'diff':'status'),null,2));}catch(e){log((e as Error).message);}continue;}if(command==='/undo'){try{log(JSON.stringify(await files.undo(new AbortController().signal)));}catch(e){log((e as Error).message);}continue;}if(command==='/retry'){if(!session.run||session.run.status==='completed'){log('No interrupted task to retry.');continue;}prompt=session.run.goal;retryNext=true;}else{log('Unknown slash command. Use /help.');continue;}}
active=new AbortController();let lastEvent='',preview='';if(session.title==='New coding session')session.title=prompt.slice(0,100);const goal=prompt;prompt='';const retry=retryNext||!!requested&&!!session.run&&session.run.status!=='completed'&&session.run.goal===goal;retryNext=false;const output=await runCodingTurn({goal,session,files,store,backend,execution,plan,maxSteps,signal:active.signal,confirm,retry,update:run=>{const e=run.events.at(-1);if(e&&e.id!==lastEvent){lastEvent=e.id;if(['action','plan','error'].includes(e.type))log('['+e.type+'] '+e.title);}},preview:text=>{if(stdin.isTTY&&!args.json){if(!preview)stdout.write('\nNova: ');stdout.write(clean(text.startsWith(preview)?text.slice(preview.length):'\n'+text));}preview=text;}});active=undefined;requested=undefined;if(args.json)stdout.write(JSON.stringify({sessionId:session.id,status:output.result.status,answer:output.result.answer,modelCalls:output.modelCalls,tokens:output.tokens,syncError:output.syncError,events:output.result.events})+'\n');else if(stdin.isTTY&&preview===output.result.answer)stdout.write('\n\n');else log('\nNova: '+output.result.answer+'\n');if(output.syncError)log('Session is saved locally; cloud sync: '+output.syncError);if(once){if(output.result.status!=='completed')process.exitCode=1;break;}}
}finally{process.removeListener('SIGINT',interrupt);}}finally{input?.close();await release();}}
if(require.main===module)void main().catch(e=>{stderr.write(clean((e as Error).message)+'\n');process.exitCode=1;});
