import {DatabaseSync} from 'node:sqlite';
import {mkdirSync,chmodSync,existsSync,readFileSync,readdirSync,lstatSync} from 'node:fs';import path from 'node:path';
import {createHash,randomBytes} from 'node:crypto';
import {validateShared} from '../../lib/agent/shared-context';import {validateSession} from './store';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export const deviceScopes=['decisions','context:read','context:write','sessions:read','sessions:write'] as const;
export class BackendDatabase{
 readonly db:DatabaseSync;readonly file:string;
 constructor(readonly directory:string){mkdirSync(directory,{recursive:true,mode:0o700});this.file=path.join(directory,'nova.sqlite');this.db=new DatabaseSync(this.file);chmodSync(this.file,0o600);this.db.exec('PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA busy_timeout=5000');const version=Number((this.db.prepare('PRAGMA user_version').get() as any).user_version);if(version>1){this.db.close();throw new Error('Backend database is newer than this Nova version');}if(version===0){this.db.exec(`BEGIN IMMEDIATE;CREATE TABLE records(scope TEXT NOT NULL,key TEXT NOT NULL,value TEXT NOT NULL,PRIMARY KEY(scope,key));CREATE TABLE devices(id TEXT PRIMARY KEY,parent TEXT NOT NULL,label TEXT NOT NULL,hash TEXT UNIQUE NOT NULL,scopes TEXT NOT NULL,created INTEGER NOT NULL,revoked INTEGER);CREATE TABLE pairings(hash TEXT PRIMARY KEY,parent TEXT NOT NULL,label TEXT NOT NULL,scopes TEXT NOT NULL,expires INTEGER NOT NULL);CREATE TABLE revoked(hash TEXT PRIMARY KEY);CREATE TABLE audit(id INTEGER PRIMARY KEY,event TEXT NOT NULL,at INTEGER NOT NULL,owner TEXT NOT NULL,detail TEXT NOT NULL);PRAGMA user_version=1;COMMIT;`);}try{this.migrateLegacy();}catch(e){this.db.close();throw e;}}
 get<T=any>(scope:string,key:string):T|undefined{const row=this.db.prepare('SELECT value FROM records WHERE scope=? AND key=?').get(scope,key) as {value:string}|undefined;return row?JSON.parse(row.value):undefined;}
 put(scope:string,key:string,value:unknown){this.db.prepare('INSERT INTO records VALUES(?,?,?) ON CONFLICT(scope,key) DO UPDATE SET value=excluded.value').run(scope,key,JSON.stringify(value));}
 list<T=any>(scope:string,prefix:string):T[]{return this.db.prepare('SELECT value FROM records WHERE scope=? AND substr(key,1,?)=?').all(scope,prefix.length,prefix).map((r:any)=>JSON.parse(r.value));}
 transaction<T>(fn:()=>T):T{this.db.exec('BEGIN IMMEDIATE');try{const result=fn();this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 audit(owner:string,event:string,detail:unknown={}){this.db.prepare('INSERT INTO audit(event,at,owner,detail) VALUES(?,?,?,?)').run(event,Date.now(),owner,JSON.stringify(detail));this.db.exec('DELETE FROM audit WHERE id <= (SELECT max(id)-2000 FROM audit)');}
 health(owner:string){return {storage:'sqlite',schemaVersion:1,audit:this.db.prepare('SELECT event,at,detail FROM audit WHERE owner=? ORDER BY id DESC LIMIT 30').all(owner).map((r:any)=>({...r,detail:JSON.parse(r.detail)}))};}
 private migrateLegacy(){if(this.get('_system','legacy-imported'))return;const imports:{scope:string;key:string;value:unknown}[]=[];const read=(file:string)=>{if(lstatSync(file).isSymbolicLink()||lstatSync(file).size>1100000)throw new Error('Unsafe or oversized legacy backend state');return JSON.parse(readFileSync(file,'utf8'));};for(const scope of readdirSync(this.directory).filter(n=>/^[a-f0-9]{32}$/.test(n))){const folder=path.join(this.directory,scope);if(lstatSync(folder).isSymbolicLink()||!lstatSync(folder).isDirectory())throw new Error('Invalid legacy backend directory');for(const name of readdirSync(folder).filter(n=>/^[-_a-zA-Z0-9]{1,80}\.json$/.test(n)).slice(0,201)){const value=validateSession(read(path.join(folder,name)));if(name!==value.id+'.json')throw new Error('Legacy session ID mismatch');imports.push({scope,key:'session:'+value.id,value});}const context=path.join(folder,'context','state.json');if(existsSync(context)){if(lstatSync(path.dirname(context)).isSymbolicLink())throw new Error('Invalid context directory');imports.push({scope,key:'context',value:validateShared(read(context))});}}
 const metrics=path.join(this.directory,'router','metrics.json');if(existsSync(metrics)){if(lstatSync(path.dirname(metrics)).isSymbolicLink())throw new Error('Invalid metrics directory');imports.push({scope:'_system',key:'metrics',value:read(metrics)});}this.transaction(()=>{for(const item of imports)if(!this.get(item.scope,item.key))this.put(item.scope,item.key,item.value);this.put('_system','legacy-imported',{at:Date.now(),records:imports.length});});}
 pair(parent:string,label:string,scopes:string[]){if(!/^[-_a-zA-Z0-9 ]{1,80}$/.test(label)||!Array.isArray(scopes)||!scopes.length||scopes.some(s=>!deviceScopes.includes(s as any)))throw new Error('Invalid device label or scopes');return this.transaction(()=>{this.db.prepare('DELETE FROM pairings WHERE expires<?').run(Date.now());const count=(this.db.prepare('SELECT count(*) AS n FROM pairings WHERE parent=?').get(parent) as any).n;if(count>=10)throw new Error('Ten active pairing codes already exist');const code=randomBytes(18).toString('base64url'),expiresAt=Date.now()+300000;this.db.prepare('INSERT INTO pairings VALUES(?,?,?,?,?)').run(hash(code),parent,label,JSON.stringify([...new Set(scopes)]),expiresAt);this.audit(parent,'pairing-created',{label,expiresAt});return {code,expiresAt,scopes};});}
 redeem(code:string){if(typeof code!=='string'||code.length>100)throw new Error('Invalid pairing code');return this.transaction(()=>{const row=this.db.prepare('SELECT * FROM pairings WHERE hash=?').get(hash(code)) as any;if(!row||row.expires<Date.now())throw new Error('Invalid or expired pairing code');const count=(this.db.prepare('SELECT count(*) AS n FROM devices WHERE parent=? AND revoked IS NULL').get(row.parent) as any).n;if(count>=50)throw new Error('Fifty active devices already exist');const token=randomBytes(32).toString('base64url'),id=crypto.randomUUID();this.db.prepare('DELETE FROM pairings WHERE hash=?').run(hash(code));this.db.prepare('INSERT INTO devices(id,parent,label,hash,scopes,created) VALUES(?,?,?,?,?,?)').run(id,row.parent,row.label,hash(token),row.scopes,Date.now());this.audit(row.parent,'device-paired',{id,label:row.label});return {token,id,label:row.label,scopes:JSON.parse(row.scopes)};});}
 authenticate(token:string){const row=this.db.prepare('SELECT * FROM devices WHERE hash=? AND revoked IS NULL').get(hash(token)) as any;return row?{id:row.id,parent:row.parent,scopes:JSON.parse(row.scopes) as string[]}:undefined;}
 revoked(token:string){return !!this.db.prepare('SELECT hash FROM revoked WHERE hash=?').get(hash(token));}
 devices(parent:string){return this.db.prepare('SELECT id,label,scopes,created,revoked FROM devices WHERE parent=? ORDER BY created DESC').all(parent).map((r:any)=>({...r,scopes:JSON.parse(r.scopes)}));}
 revoke(parent:string,id:string){const found=this.db.prepare('SELECT id FROM devices WHERE id=? AND parent=?').get(id,parent);if(!found)throw new Error('Device not found');this.db.prepare('UPDATE devices SET revoked=? WHERE id=? AND parent=?').run(Date.now(),id,parent);this.audit(parent,'device-revoked',{id});}
 backup(){const folder=path.join(this.directory,'backups');mkdirSync(folder,{recursive:true,mode:0o700});if(readdirSync(folder).filter(n=>/^nova-.*\.sqlite$/.test(n)).length>=10)throw new Error('Ten backend snapshots exist; archive them before creating another');const file=path.join(folder,'nova-'+Date.now()+'-'+randomBytes(4).toString('hex')+'.sqlite');this.db.prepare('VACUUM INTO ?').run(file);chmodSync(file,0o600);return {filename:path.basename(file),createdAt:Date.now(),schemaVersion:1};}
 close(){this.db.close();}
}
