import type {RemoteConfig} from './config';import type {AgentMessage} from '../../lib/agent/types';import type {CodingSession} from './store';import {readModelStream} from '../../lib/agent/stream';
export class BackendClient{model?:string;constructor(readonly config:RemoteConfig){}async request(route:string,options:RequestInit={},signal?:AbortSignal){const response=await fetch(this.config.backend+route,{...options,redirect:'error',headers:{Authorization:'Bearer '+this.config.token,'Content-Type':'application/json',...options.headers},signal:signal?AbortSignal.any([signal,AbortSignal.timeout(110000)]):AbortSignal.timeout(15000)});if(!response.ok){let error='Backend HTTP '+response.status;try{const data:any=await response.json();error=data.error||error;}catch{}throw Object.assign(new Error(error),{status:response.status});}return response;}
async live(){return (await(await this.request('/v1/live')).json()) as {sessions:any[]};}
async claim(session:CodingSession){return (await(await this.request('/v1/live/'+session.id+'/claim',{method:'POST',body:JSON.stringify({session})})).json()) as {leaseId:string;revision:number};}
async checkpoint(session:CodingSession,leaseId:string,status='running'){return (await(await this.request('/v1/live/'+session.id+'/checkpoint',{method:'POST',body:JSON.stringify({session,leaseId,status})})).json()) as {revision:number;controls:{id:string;type:'stop'|'steer';text?:string}[]};}
async control(id:string,type:'stop'|'steer',text?:string){return (await(await this.request('/v1/live/'+id+'/control',{method:'POST',body:JSON.stringify({type,text})})).json());}
async info(){const data:any=await(await this.request('/v1/info')).json();if(data.protocol!=='nova-cli/1')throw new Error('This URL does not implement the Nova CLI backend protocol');return data;}
async decision(system:string,messages:AgentMessage[],signal:AbortSignal,preview:(answer:string)=>void){const response=await this.request('/v1/decision',{method:'POST',body:JSON.stringify({system,messages,stream:true,model:this.model})},signal);let usage:Record<string,number>|undefined;const text=await readModelStream(response,signal,preview,value=>{usage={...usage,...value};});return {text,usage};}
async context(){return (await(await this.request('/v1/context')).json()) as import('../../lib/agent/shared-context').SharedContext;}
async saveContext(context:import('../../lib/agent/shared-context').SharedContext){return (await(await this.request('/v1/context',{method:'PUT',body:JSON.stringify(context)})).json()) as import('../../lib/agent/shared-context').SharedContext;}
async list(projectId:string){return (await(await this.request('/v1/sessions?projectId='+encodeURIComponent(projectId))).json()) as {sessions:CodingSession[]};}
async load(id:string){return (await(await this.request('/v1/sessions/'+encodeURIComponent(id))).json()) as {session:CodingSession};}
async save(session:CodingSession){const data:any=await(await this.request('/v1/sessions/'+encodeURIComponent(session.id),{method:'PUT',body:JSON.stringify({session,revision:session.revision})})).json();return data.revision as number;}}
