'use client';import {useEffect,useRef,useState} from 'react';
type Result={answer:string;status:string};
export default function RealtimeVoiceChat({onTask,onTranscript}:{onTask:(goal:string)=>Promise<Result>;onTranscript:(role:'user'|'assistant',text:string)=>void}){const [active,setActive]=useState(false),[status,setStatus]=useState(''),peer=useRef<RTCPeerConnection|null>(null),channel=useRef<RTCDataChannel|null>(null),stream=useRef<MediaStream|null>(null),audio=useRef<HTMLAudioElement|null>(null),abort=useRef<AbortController|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),callbacks=useRef({onTask,onTranscript});callbacks.current={onTask,onTranscript};
function stop(){abort.current?.abort();abort.current=null;if(timer.current)clearTimeout(timer.current);timer.current=null;channel.current?.close();channel.current=null;peer.current?.close();peer.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(audio.current){audio.current.pause();audio.current.srcObject=null;}audio.current=null;setActive(false);}
useEffect(()=>()=>stop(),[]);
async function start(){stop();const controller=new AbortController();abort.current=controller;setActive(true);setStatus('Connecting live voice…');try{if(!window.RTCPeerConnection||!navigator.mediaDevices)throw new Error('Live voice requires a secure browser with microphone and WebRTC support');const mic=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true}});if(controller.signal.aborted){mic.getTracks().forEach(t=>t.stop());return;}stream.current=mic;const pc=new RTCPeerConnection();peer.current=pc;const player=new Audio();audio.current=player;player.autoplay=true;pc.ontrack=e=>{player.srcObject=e.streams[0];void player.play().catch(()=>setStatus('Tap Live voice again if your browser blocks audio.'));};for(const track of mic.getTracks())pc.addTrack(track,mic);const dc=pc.createDataChannel('oai-events');channel.current=dc;const seen=new Set<string>();let tasks=0,pending=false;
dc.onopen=()=>setStatus('Live voice · speak naturally; interrupt to pause Nova’s speech.');dc.onmessage=event=>{let data:any;try{data=JSON.parse(event.data);}catch{return;}if(data.type==='error'){setStatus(data.error?.message||'Voice provider error');return;}if(data.type==='input_audio_buffer.speech_started')setStatus('Listening · speech interrupted');if(data.type==='conversation.item.input_audio_transcription.completed')callbacks.current.onTranscript('user',data.transcript||'');if(data.type==='response.output_audio_transcript.done')callbacks.current.onTranscript('assistant',data.transcript||'');if(data.type==='response.function_call_arguments.done'&&data.name==='nova_task'&&!seen.has(data.call_id)){seen.add(data.call_id);const reply=(result:Result)=>{if(dc.readyState!=='open')return;dc.send(JSON.stringify({type:'conversation.item.create',item:{type:'function_call_output',call_id:data.call_id,output:JSON.stringify(result)}}));dc.send(JSON.stringify({type:'response.create'}));};let goal='';try{const args=JSON.parse(data.arguments);if(typeof args.goal!=='string'||!args.goal.trim()||args.goal.length>12000||Object.keys(args).some(k=>k!=='goal'))throw new Error();goal=args.goal;}catch{reply({status:'failed',answer:'Invalid task request'});return;}if(pending||++tasks>20){reply({status:'limited',answer:'A task is running or this voice session reached its task cap.'});return;}pending=true;setStatus('Nova is working · review requested approvals in chat.');void callbacks.current.onTask(goal).then(reply).catch(e=>reply({status:'failed',answer:e.message})).finally(()=>{pending=false;});}};
pc.onconnectionstatechange=()=>{if(['failed','disconnected'].includes(pc.connectionState)){stop();setStatus('Live voice disconnected.');}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await fetch('/api/realtime',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({sdp:offer.sdp}),signal:controller.signal});if(!response.ok){const data:any=await response.json();throw new Error(data.error||'Voice connection failed');}await pc.setRemoteDescription({type:'answer',sdp:await response.text()});timer.current=setTimeout(()=>{stop();setStatus('Voice session ended after 10 minutes. Start again to continue.');},600000);}catch(e){if(!controller.signal.aborted){stop();setStatus((e as Error).message);}}}
return <span><button type="button" title="Continuous voice with interruption; microphone audio goes to your speech provider" onClick={()=>active?stop():void start()}>{active?'Stop live voice':'Live voice'}</button>{status&&<small role="status">{status}</small>}</span>;}
