'use client';
import {useEffect,useRef,useState} from 'react';import type {Chat} from '../../lib/agent/chats';
export default function useSyncedChats(){const [chats,render]=useState<Chat[]>([]),[syncError,setError]=useState(''),[loaded,setLoaded]=useState(false);const current=useRef<Chat[]>([]),dirty=useRef(new Map<string,Chat>()),revisions=useRef(new Map<string,number>()),working=useRef(false),ready=useRef(false);
function display(next:Chat[]){current.current=next;render(next);try{localStorage.setItem('nova-chats',JSON.stringify(next));}catch{setError('Browser backup is full. Export important chats.');}}
function setChats(change:Chat[]|((old:Chat[])=>Chat[])){const old=current.current,next=typeof change==='function'?change(old):change;for(const chat of next)if(JSON.stringify(old.find(c=>c.id===chat.id))!==JSON.stringify(chat))dirty.current.set(chat.id,chat);for(const chat of old)if(!next.some(c=>c.id===chat.id))dirty.current.set(chat.id,{...chat,archived:true});display(next);}
async function sync(){if(working.current||!ready.current)return;working.current=true;try{for(const [id,chat] of [...dirty.current]){const response=await fetch('/api/chats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat,revision:revisions.current.get(id)})});const data:any=await response.json();if(response.status===409){const copy={...chat,id:crypto.randomUUID(),title:chat.title+' (recovered draft)'};dirty.current.delete(id);if(!chat.archived){dirty.current.set(copy.id,copy);display([copy,...current.current.filter(c=>c.id!==id)]);}setError('Another device changed this chat. Your changes were preserved in a recovered draft.');continue;}if(!response.ok)throw new Error(data.error);revisions.current.set(id,data.revision);if(dirty.current.get(id)===chat)dirty.current.delete(id);}
const response=await fetch('/api/chats',{cache:'no-store'});const data:any=await response.json();if(!response.ok)throw new Error(data.error);const remote:Chat[]=[];for(const item of data.chats){if(!dirty.current.has(item.chat.id)){revisions.current.set(item.chat.id,item.revision);if(!item.chat.archived)remote.push(item.chat);}}display([...current.current.filter(c=>dirty.current.has(c.id)),...remote].sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)));}catch(e){setError('Conversation sync: '+(e as Error).message);}finally{working.current=false;}}
useEffect(()=>{let stopped=false;void(async()=>{let legacy:Chat[]=[];try{legacy=JSON.parse(localStorage.getItem('nova-chats')||'[]');}catch{}try{const response=await fetch('/api/chats');const data:any=await response.json();if(!response.ok)throw new Error(data.error);if(stopped)return;const remote=data.chats.map((item:any)=>{revisions.current.set(item.chat.id,item.revision);return item.chat as Chat;});for(const chat of legacy){const server=remote.find((c:Chat)=>c.id===chat.id);if(!server){dirty.current.set(chat.id,chat);remote.push(chat);}}display(remote.filter((c:Chat)=>!c.archived));ready.current=true;setLoaded(true);void sync();}catch(e){if(stopped)return;display(legacy);setError('Conversation sync unavailable: '+(e as Error).message);ready.current=true;for(const chat of legacy)dirty.current.set(chat.id,chat);setLoaded(true);}})();const timer=setInterval(()=>void sync(),5000);return()=>{stopped=true;clearInterval(timer);};},[]);
return {chats,setChats,syncError,loaded,sync};}
