'use client';
import type {ProviderConfig} from '../../lib/agent/types';
import {useEffect,useRef,useState} from 'react';
export default function VoiceInput({onText,disabled,vision}:{onText:(text:string)=>void;disabled:boolean;vision:ProviderConfig}){
 const [listening,setListening]=useState(false),[wake,setWake]=useState(false),[error,setError]=useState(''),[settings,setSettings]=useState(false),[base,setBase]=useState('https://api.openai.com/v1'),[key,setKey]=useState(''),[model,setModel]=useState('whisper-1'),[busy,setBusy]=useState(false);
 const recognition=useRef<any>(null),upload=useRef<HTMLInputElement>(null),callback=useRef(onText);callback.current=onText;
 useEffect(()=>()=>{recognition.current?.abort();},[]);
 function stop(){recognition.current?.abort();recognition.current=null;setListening(false);}
 function start(){setError('');const ctor=(window as any).SpeechRecognition||(window as any).webkitSpeechRecognition;if(!ctor){setError('Live dictation is unavailable in this browser. Upload audio with a transcription provider instead.');return;}const r=new ctor();r.continuous=true;r.interimResults=false;r.lang=navigator.language;let activated=!wake;recognition.current=r;r.onstart=()=>setListening(true);r.onend=()=>{setListening(false);recognition.current=null;};r.onerror=(e:any)=>{setError('Microphone: '+e.error);stop();};r.onresult=(event:any)=>{for(let i=event.resultIndex;i<event.results.length;i++){if(!event.results[i].isFinal)continue;let text=event.results[i][0].transcript.trim();if(!activated){const match=/hey nova\b/i.exec(text);if(!match)continue;activated=true;text=text.slice(match.index+match[0].length).trim();}if(text)callback.current(text);}};r.start();}
 async function transcribe(file:File){if(file.type.startsWith('image/')){setBusy(true);setError('');try{if(file.size>5000000)throw new Error('Image must be smaller than 5 MB');const image=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error('Could not read image'));reader.readAsDataURL(file);});const response=await fetch('/api/describe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image,connectionId:vision.connectionId,base:vision.base,key:vision.key,model:vision.model,protocol:vision.protocol})});const result=await response.json() as {text:string;error?:string};if(!response.ok)throw new Error(result.error||'Image transcription failed');callback.current('[Image transcript: '+file.name+']\n'+result.text);setSettings(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}return;}
 setBusy(true);setError('');try{if(file.size>10000000)throw new Error('Audio must be smaller than 10 MB');const data=new FormData();data.set('audio',file);data.set('base',base);data.set('key',key);data.set('model',model);const response=await fetch('/api/transcribe',{method:'POST',body:data});const result=await response.json() as {text:string;error?:string};if(!response.ok)throw new Error(result.error||'Transcription failed');callback.current(result.text);setSettings(false);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <span className="voiceinput"><button disabled={disabled||busy} title={listening?'Stop microphone':'Start dictation'} onClick={()=>listening?stop():start()}>{listening?'● Listening':'Mic'}</button><button disabled={disabled||listening} onClick={()=>setSettings(v=>!v)} title="Voice memo and wake phrase settings">Voice</button>{settings&&<div className="voicepopover"><strong>Voice input</strong><label><input type="checkbox" checked={wake} disabled={listening} onChange={e=>setWake(e.target.checked)}/>Wait for “Hey Nova” while listening</label><p>Start the microphone explicitly. Recognition works while this page is open; your browser may send audio to its speech service. Dictation fills the message box; you review and send.</p><label>Transcription API base<input value={base} onChange={e=>setBase(e.target.value)}/></label><label>Speech API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)}/></label><label>Speech model<input value={model} onChange={e=>setModel(e.target.value)}/></label><button disabled={busy} onClick={()=>upload.current?.click()}>{busy?'Transcribing…':'Upload audio or image'}</button><p>Audio uses the speech endpoint. Images use your selected vision-capable chat model. Credentials remain in this panel’s memory.</p></div>}{error&&<span role="alert" className="help">{error}<button onClick={()=>setError('')}>Dismiss</button></span>}<input ref={upload} hidden type="file" accept="audio/*,video/mp4,image/png,image/jpeg,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void transcribe(file);e.target.value='';}}/></span>;
}
