'use client';
import { useRef, useState } from 'react';
import { Brain, FolderOpen, FileText, Clock, Plus, Trash2, Download, X, Check, Upload, RotateCcw, ArrowLeft } from 'lucide-react';
import type { AgentRun } from '../../lib/agent/types';
import type { NovaRuntime } from './useNova';
import ReadinessPanel from './ReadinessPanel';
import LearningPanel from './LearningPanel';
import DeviceHubPanel from './DeviceHubPanel';
import CompanionPanel from './CompanionPanel';
import RecoveryPanel from './RecoveryPanel';
import AuditPanel from './AuditPanel';
import OperatorsPanel from './OperatorsPanel';
import JobsPanel from './JobsPanel';
import { profiles, parseSkill } from '../../lib/agent/framework';
import { safePath } from '../../lib/agent/records';
export function download(name: string, content: string, type = 'text/plain') { const url = URL.createObjectURL(new Blob([content], { type })); const link = document.createElement('a'); link.href = url; link.download = name.split('/').pop() || 'nova-file.txt'; link.click(); URL.revokeObjectURL(url); }
export default function WorkspacePanel({ runtime, initialTab = 'files', onClose, onOpenRun, onDiscuss, onImport }: { runtime: NovaRuntime; onImport?:(session:any)=>void; onDiscuss?:(text:string)=>void; initialTab?: string; onClose: () => void; onOpenRun: (run: AgentRun) => void }) {
  const [tab, setTab] = useState(initialTab), [error, setError] = useState(''), [draft, setDraft] = useState<{ kind: 'file' | 'memory'; id?: string; name: string; content: string } | null>(null);
  const upload = useRef<HTMLInputElement>(null);
  const files = runtime.records.filter(r => r.kind === 'file'), notes = runtime.records.filter(r => r.kind === 'memory'), runs = runtime.records.filter(r => r.kind === 'run').sort((a,b) => b.updatedAt - a.updatedAt);
  return <div className="overlay" onClick={onClose}><section className="workspaceModal" role="dialog" aria-modal="true" aria-label="Nova workspace" onClick={e => e.stopPropagation()}><div className="modaltitle"><div><span className="eyebrow">PART OF YOUR CONVERSATION</span><h2>Your workspace.</h2><p className="help">Files, lasting memory, and saved activity for the same Nova assistant.</p></div><button onClick={onClose} aria-label="Close workspace"><X size={21} /></button></div>
    {(error || runtime.storageError) && <div className="agenterror">{error || runtime.storageError}<button onClick={() => runtime.refresh().catch(e => setError(e.message))}>Retry</button></div>}
    {draft ? <div className="workspaceeditor"><button onClick={() => setDraft(null)}><ArrowLeft size={14} /> Back</button><label>{draft.kind === 'file' ? 'Relative file path' : 'Memory title'}<input value={draft.name} disabled={!!draft.id} onChange={e => setDraft({ ...draft, name: e.target.value })} /></label><label>Content<textarea rows={13} value={draft.content} onChange={e => setDraft({ ...draft, content: e.target.value })} /></label><button className="done" disabled={!draft.name.trim() || runtime.running} onClick={async () => { try { if (draft.kind === 'file') { safePath(draft.name); if (/^skills\/[a-z0-9-]+\.json$/.test(draft.name)) { const skill = parseSkill(draft.content); if (draft.name !== 'skills/' + skill.name + '.json') throw new Error('The file path must match skills/' + skill.name + '.json'); } } await runtime.saveRecord({ id: draft.id || (draft.kind === 'file' ? 'file:' + draft.name : 'memory:' + crypto.randomUUID()), kind: draft.kind, name: draft.name, content: draft.content, updatedAt: Date.now() }); setDraft(null); setError(''); } catch (e) { setError((e as Error).message); } }}><Check size={16} /> Save</button></div> : <><div className="agenttabs"><button className={tab==='readiness'?'active':''} onClick={()=>setTab('readiness')}>Setup readiness</button><button className={tab==='learning'?'active':''} onClick={()=>setTab('learning')}>Learning review</button><button className={tab==='hub'?'active':''} onClick={()=>setTab('hub')}>Devices & sync</button><button className={tab==='companion'?'active':''} onClick={()=>setTab('companion')}>Goals & growth</button><button className={tab==='recovery'?'active':''} onClick={()=>setTab('recovery')}>Backup & health</button><button className={tab==='operators'?'active':''} onClick={()=>setTab('operators')}>Operator setup</button><button className={tab==='audit'?'active':''} onClick={()=>setTab('audit')}>Audit & safety</button><button className={tab === 'framework' ? 'active' : ''} onClick={() => setTab('framework')}>Profile & skills</button><button className={tab === 'jobs' ? 'active' : ''} onClick={() => setTab('jobs')}>Automation</button><button className={tab === 'files' ? 'active' : ''} onClick={() => setTab('files')}><FolderOpen size={15} /> Files · {files.length}</button><button className={tab === 'memory' ? 'active' : ''} onClick={() => setTab('memory')}><Brain size={15} /> Memory · {notes.length}</button><button className={tab === 'runs' ? 'active' : ''} onClick={() => setTab('runs')}><Clock size={15} /> Activity · {runs.length}</button></div><div className="workspacebody">
    {tab==='readiness'&&<ReadinessPanel/>}
    {tab==='learning'&&<LearningPanel/>}
    {tab==='hub'&&<DeviceHubPanel onImport={onImport}/>}
    {tab==='companion'&&<CompanionPanel runtime={runtime} onDiscuss={onDiscuss}/>}
    {tab==='recovery'&&<RecoveryPanel/>}
    {tab === 'audit' && <><p className="help">Permission level: {runtime.capabilities.permissionLevel||'workspace'}. Sensitive actions need sign-off. Three repeated failures open a circuit breaker and stop the run.</p><AuditPanel runtime={runtime}/></>}
    {tab === 'operators' && <OperatorsPanel/>}
    {tab === 'jobs' && <JobsPanel />}
    {tab === 'framework' && <><div className="frameworkintro"><h3>One assistant. A lasting identity.</h3><p>Nova loads these documents at the start of each response. Verified activity is recorded in memory.md; successful read-only workflows are automatically captured as parameterized SKILL.md procedures.</p></div><div className="memorycards">{Object.entries(profiles).map(([name, fallback]) => { const record = files.find(r => r.name === name); return <article key={name}><strong>{name}</strong><p>{name === 'soul.md' ? 'Identity, tone, and behavioral directives.' : name === 'user.md' ? 'Confirmed preferences and environment.' : 'Persistent context and reflection history.'}</p><button disabled={runtime.running} onClick={() => setDraft({ kind: 'file', id: record?.id, name, content: record?.content || fallback })}>Edit document</button></article>; })}</div><div className="panelheading"><h3>Reusable skills</h3><button onClick={() => setDraft({ kind: 'file', name: 'skills/new-skill.json', content: JSON.stringify({ name: 'new-skill', description: 'Describe when to use this routine.', steps: [{ name: 'calculate', args: { expression: '2+2' } }] }, null, 2) })}>New skill</button></div><p className="help">Skills are validated tool workflows. Ask Nova to save a successful routine, then run it by name in chat. Commands run in Docker and still require approval. Generated code can be saved as files and executed locally through an approved command.</p><div className="recordlist">{files.filter(r => /^skills\/[a-z0-9-]+\.json$/.test(r.name)).map(record => <div key={record.id}><FileText size={18}/><button onClick={() => setDraft({ ...record, kind: 'file' })}><strong>{record.name}</strong><small>Edit steps and description</small></button><button title="Delete skill" disabled={runtime.running} onClick={() => runtime.remove(record).catch(e => setError(e.message))}><Trash2 size={15}/></button></div>)}</div></>}
    {tab === 'files' && <><div className="panelheading"><p>{runtime.capabilities.runtime === 'local' ? 'Real files in your local workspace folder.' : 'Private cloud files that Nova can read and write.'}</p><div><button onClick={() => upload.current?.click()}><Upload size={15} /> Upload text</button><button onClick={() => setDraft({ kind: 'file', name: '', content: '' })}><Plus size={15} /> New file</button></div></div>{!files.length && <p className="paneempty">Attach a text file in chat or ask Nova to create one.</p>}<div className="recordlist">{files.map(record => <div key={record.id}><FileText size={18} /><button onClick={() => setDraft({ ...record, kind: 'file' })}><strong>{record.name}</strong><small>{record.content.length.toLocaleString()} characters</small></button><button title="Download file" onClick={() => download(record.name, record.content)}><Download size={15} /></button><button title="Delete file" disabled={runtime.running} onClick={() => runtime.remove(record).catch(e => setError(e.message))}><Trash2 size={15} /></button></div>)}</div></>}
    {tab === 'memory' && <><div className="panelheading"><p>Preferences and notes used in every conversation.</p><button onClick={() => setDraft({ kind: 'memory', name: '', content: '' })}><Plus size={15} /> Add note</button></div>{!notes.length && <p className="paneempty">Tell Nova “remember…” in chat, or add a note here.</p>}<div className="memorycards">{notes.map(record => <article key={record.id}><div><Brain size={17} /><strong>{record.name}</strong><button title="Delete memory" disabled={runtime.running} onClick={() => runtime.remove(record).catch(e => setError(e.message))}><Trash2 size={14} /></button></div><p>{record.content}</p><button onClick={() => setDraft({ ...record, kind: 'memory' })}>Edit note</button></article>)}</div></>}
    {tab === 'runs' && <><div className="panelheading"><p>Open a previous response or continue interrupted work in chat.</p><button onClick={() => runtime.refresh().catch(e => setError(e.message))}><RotateCcw size={15} /> Refresh</button></div>{!runs.length && <p className="paneempty">Your saved responses and tool activity will appear here.</p>}<div className="recordlist">{runs.map(record => <div key={record.id}><Clock size={18} /><button disabled={runtime.running} onClick={() => { try { const saved = JSON.parse(record.content) as AgentRun; if (saved.status === 'running') { saved.status = 'paused'; saved.answer = 'This response was interrupted. Resume to continue.'; } onOpenRun(saved); onClose(); } catch { setError('This activity could not be opened.'); } }}><strong>{record.name}</strong><small>{new Date(record.updatedAt).toLocaleString()}</small></button><button title="Delete saved activity" disabled={runtime.running} onClick={() => runtime.remove(record).catch(e => setError(e.message))}><Trash2 size={15} /></button></div>)}</div></>}
    </div><div className="workspacesettings"><label>Maximum steps per response <select value={runtime.steps} disabled={runtime.running} onChange={e => runtime.setSteps(Number(e.target.value))}>{[6,12,20,40].map(value => <option key={value}>{value}</option>)}</select></label><span>{runtime.capabilities.terminalEnabled ? 'Docker commands require approval' : 'Tools are available directly in chat'}</span></div></>}
    <input ref={upload} type="file" hidden accept=".txt,.md,.csv,.json,.js,.ts,.tsx,.py,.html,.css,.xml,.yaml,.yml,.log" onChange={async e => { const file = e.target.files?.[0]; if (file) { try { if (file.size > 200000) throw new Error('Use a text file smaller than 200 KB.'); safePath(file.name); await runtime.saveRecord({ id: 'file:' + file.name, kind: 'file', name: file.name, content: await file.text(), updatedAt: Date.now() }); } catch (e) { setError((e as Error).message); } } e.target.value = ''; }} />
  </section></div>;
}
