import type {AgentMessage,ProviderConfig} from './types';
import {openModelResponse} from './model-client';
export type RouteRole='general'|'coding'|'reasoning'|'fast';
export type GatewayRoute={id:string;role:RouteRole;priority:number;enabled:boolean;inputPrice?:number;outputPrice?:number;contextTokens?:number;quality?:number};
export type GatewayPolicy={mode:'balanced'|'local-first'|'local-only'|'cloud-only';fallback:boolean;selection?:'balanced'|'latency'|'cost'|'quality';routes:GatewayRoute[]};
export type RouteCandidate=GatewayRoute&{config:ProviderConfig;name?:string;metrics?:{samples:number;latencyMs:number;failures:number}};
export const defaultPolicy:GatewayPolicy={mode:'balanced',fallback:false,routes:[]};
export function isLocal(base:string){try{return ['localhost','127.0.0.1','[::1]'].includes(new URL(base).hostname);}catch{return false;}}
export function validatePolicy(value:any):GatewayPolicy{
 if(!value||!['balanced','local-first','local-only','cloud-only'].includes(value.mode)||typeof value.fallback!=='boolean'||!Array.isArray(value.routes)||value.routes.length>20)throw new Error('Invalid gateway policy');
 if(value.selection&&!['balanced','latency','cost','quality'].includes(value.selection))throw new Error('Invalid routing preference');const ids=new Set<string>();const routes=value.routes.map((r:any)=>{if(!r||typeof r.id!=='string'||!/^[-_a-zA-Z0-9]{1,80}$/.test(r.id)||ids.has(r.id)||!['general','coding','reasoning','fast'].includes(r.role)||!Number.isInteger(r.priority)||r.priority<0||r.priority>99||typeof r.enabled!=='boolean')throw new Error('Invalid or duplicate gateway route');ids.add(r.id);const extra:any={};for(const key of ['inputPrice','outputPrice','contextTokens','quality'])if(r[key]!==undefined){if(!Number.isFinite(r[key])||r[key]<0||r[key]>(key==='contextTokens'?10000000:key==='quality'?100:10000))throw new Error('Invalid route '+key);extra[key]=r[key];}return {...extra,id:r.id,role:r.role,priority:r.priority,enabled:r.enabled} as GatewayRoute;});return {mode:value.mode,fallback:value.fallback,selection:value.selection||'balanced',routes};
}
export function taskRole(messages:AgentMessage[]):RouteRole{const text=messages.find(m=>m.role==='user')?.content.slice(0,12000)||'';if(/\b(code|coding|repository|repo|debug|compiler|typescript|python|javascript|test suite|function|patch)\b/i.test(text))return 'coding';if(/\b(plan|strategy|analyse|analyze|reason|compare|ambition|goal|research)\b/i.test(text))return 'reasoning';if(text.length<250)return 'fast';return 'general';}
export function orderedRoutes(policy:GatewayPolicy,candidates:RouteCandidate[],messages:AgentMessage[],allowLocal:boolean,system=''){const role=taskRole(messages),estimatedTokens=Math.ceil((system.length+messages.reduce((n,m)=>n+m.content.length,0))/3)+4096;
const score=(r:RouteCandidate)=>r.priority+(r.role===role?200:r.role==='general'?100:0)+(policy.mode==='local-first'&&isLocal(r.config.base)?1000:0);
const preference=(r:RouteCandidate)=>policy.selection==='latency'?r.metrics?.samples?r.metrics.latencyMs:Infinity:policy.selection==='cost'?r.inputPrice!==undefined&&r.outputPrice!==undefined?r.inputPrice*estimatedTokens+r.outputPrice*4096:Infinity:policy.selection==='quality'?-(r.quality??0):0;
const routes=candidates.filter(r=>r.enabled&&(!r.contextTokens||r.contextTokens>=estimatedTokens)&&(allowLocal||!isLocal(r.config.base))&&(policy.mode!=='local-only'||isLocal(r.config.base))&&(policy.mode!=='cloud-only'||!isLocal(r.config.base))).sort((a,b)=>{const local=policy.mode==='local-first'?Number(isLocal(b.config.base))-Number(isLocal(a.config.base)):0;return local||preference(a)-preference(b)||score(b)-score(a)||a.id.localeCompare(b.id);});if(!routes.length)throw new Error(policy.mode==='local-only'&&!allowLocal?'Local-only routing requires Nova running on your device or a local CLI backend. A hosted server cannot reach your laptop localhost.':'No eligible gateway routes. Check enabled routes, locality and declared context capacity.');return routes.slice(0,policy.fallback?3:1);}
export async function openGateway(policy:GatewayPolicy,candidates:RouteCandidate[],system:string,messages:AgentMessage[],signal:AbortSignal,allowLocal=false,stream=true,observe?:(event:{id:string;latencyMs:number;failed:boolean})=>Promise<void>){const routes=orderedRoutes(policy,candidates,messages,allowLocal,system);const failures:{id:string;status:number}[]=[];for(const route of routes){signal.throwIfAborted();const started=Date.now();try{const result=await openModelResponse({...route.config,fallbackModel:undefined},system,messages,signal,allowLocal,stream);await observe?.({id:route.id,latencyMs:Date.now()-started,failed:false}).catch(()=>{});return {...result,protocol:route.config.protocol,routeId:route.id,routeName:route.name||route.id,failovers:failures};}catch(e){signal.throwIfAborted();const status=Number((e as any).status||0);failures.push({id:route.id,status});await observe?.({id:route.id,latencyMs:Date.now()-started,failed:true}).catch(()=>{});if(status&&![408,429,500,502,503,504].includes(status))throw e;if(route===routes.at(-1))throw new Error('Configured gateway routes are unavailable ('+failures.map(f=>f.id+': '+(f.status||'connection failure')).join(', ')+')');}}throw new Error('No route');}
