import type {AgentMessage,ProviderConfig} from './types';import type {ModelReply} from './operations';import {publicHttps} from './http';
const decision={name:'nova_decision',description:'Return the next Nova agent action or final answer.',parameters:{type:'object',properties:{type:{type:'string',enum:['plan','tool','parallel','final']},name:{type:'string'},args:{type:'object',additionalProperties:true},answer:{type:'string'},steps:{type:'array',items:{type:'string'}},tools:{type:'array',items:{type:'object',properties:{name:{type:'string'},args:{type:'object',additionalProperties:true}},required:['name','args']} }},required:['type']}};
export function decisionBody(config:ProviderConfig,messages:AgentMessage[],system:string,stream=false,native=true){const anthropic=config.protocol==='anthropic';const body:any=anthropic?{model:config.model,system,messages,max_tokens:4096,stream}:{model:config.model,messages:[{role:'system',content:system},...messages],stream};if(native){body.tools=anthropic?[{name:decision.name,description:decision.description,input_schema:decision.parameters}]:[{type:'function',function:decision}];body.tool_choice=anthropic?{type:'tool',name:decision.name}:{type:'function',function:{name:decision.name}};}return body;}
export function replyText(data:any,protocol:string){return protocol==='anthropic'?data.content?.map((c:any)=>c.type==='tool_use'&&c.name==='nova_decision'?JSON.stringify(c.input):c.type==='text'?c.text:'').join(''):data.choices?.[0]?.message?.tool_calls?.find((t:any)=>t.function?.name==='nova_decision')?.function?.arguments||data.choices?.[0]?.message?.content;}
export async function openModelResponse(config:ProviderConfig,system:string,messages:AgentMessage[],signal:AbortSignal,allowLocal=false,stream=false){const root=config.base.replace(/\/+$/,'');const url=new URL(root);const loopback=allowLocal&&['127.0.0.1','localhost','[::1]'].includes(url.hostname)&&['http:','https:'].includes(url.protocol)&&!url.username&&!url.password;if(!loopback)publicHttps(root);if(!config.model)throw new Error('Choose a model');if(!config.key&&!loopback)throw new Error('Add an API key');let last:Error|undefined,native=true;for(let attempt=0;attempt<3;attempt++){signal.throwIfAborted();const model=attempt===2&&config.fallbackModel?config.fallbackModel:config.model;let response:Response;
try{response=await fetch(root+(config.protocol==='anthropic'?'/messages':'/chat/completions'),{method:'POST',redirect:'error',signal:AbortSignal.any([signal,AbortSignal.timeout(90000)]),headers:{'Content-Type':'application/json',...(config.protocol==='anthropic'?{'x-api-key':config.key,'anthropic-version':'2023-06-01'}:config.key?{Authorization:'Bearer '+config.key}:{})},body:JSON.stringify(decisionBody({...config,model},messages,system,stream,native))});}catch(e){signal.throwIfAborted();last=e as Error;if(attempt===2)throw last;continue;}
if(response.ok)return {response,model};let message='Model provider HTTP '+response.status;try{const error:any=await response.json();message=error.error?.message||error.message||message;}catch{}last=Object.assign(new Error(message),{status:response.status});if(response.status===400&&native){native=false;continue;}if(![429,500,502,503,504].includes(response.status))throw last;if(attempt<2){const retry=Number(response.headers.get('retry-after'));const ms=Math.min(5000,Number.isFinite(retry)&&retry>0?retry*1000:500*2**attempt);await new Promise<void>((resolve,reject)=>{const timer=setTimeout(()=>{signal.removeEventListener('abort',stop);resolve();},ms);function stop(){clearTimeout(timer);reject(signal.reason);}signal.addEventListener('abort',stop,{once:true});});}}
throw last||new Error('Model request failed');}
export async function requestModel(config:ProviderConfig,system:string,messages:AgentMessage[],signal:AbortSignal,allowLocal=false):Promise<ModelReply>{const {response,model}=await openModelResponse(config,system,messages,signal,allowLocal);const data:any=await response.json();const text=replyText(data,config.protocol);if(typeof text!=='string'||!text)throw new Error('No agent decision returned');return {text,usage:data.usage,model};}
